# Generated by Django 5.2.10 on 2026-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docmodel',
            old_name='vid',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='docmodel',
            old_name='date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='docmodel',
            name='stoken',
        ),
        migrations.AddField(
            model_name='docmodel',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
    ]
